all: A8p1 A8p2_shm A8p2_unixpipe A8p2_namedpipe

A8p1: A8p1.c
	gcc A8p1.c -o A8p1

A8p2_shm: A8p2_shm.c
	gcc A8p2_shm.c -lrt -o A8p2_shm

A8p2_unixpipe: A8p2_unixpipe.c
	gcc A8p2_unixpipe.c -o A8p2_unixpipe

A8p2_namedpipe: A8p2_namedpipe.c
	gcc A8p2_namedpipe.c -o A8p2_namedpipe